// The 32 ovals of NASCAR mode: published specs, used by train/nascar/fetch-tracks.js to bake js/nascar-tracks.js.
//
// Sources: banking and lengths from the track list on Wikipedia (List of NASCAR tracks, 2024 season) and
// NASCAR.com; pole speeds from NASCAR.com / track press releases / SpeedwayMedia qualifying reports (2025
// unless noted). `pole.fit` marks the Next Gen (2022+) Cup laps the physics is calibrated against; older eras
// and other series are shown for reference only. Widths and aprons are approximate where no figure is
// published (marked approx).
//
// banking: degrees. turns = each corner complex in the order a car meets them after the start/finish line;
// [low, high] = progressive banking (higher lanes steeper). front/back = straights; tri = tri-oval/dogleg.
// shape: the fallback layout if OpenStreetMap has no clean loop. sf: where the start/finish line is
// ('bulge' = the frontstretch bows out as on tri-ovals and D-ovals, 'longest' = middle of the longest straight).
const SPECS = [
  // ---- superspeedways: tapered spacer ("restrictor plate"), 510 hp, pack racing ----
  { id: 'daytona', name: 'Daytona International Speedway', short: 'Daytona', lat: 29.1852, lon: -81.0705, miles: 2.5,
    banking: { turns: [31, 31], front: 18, back: 2 }, widthFt: 40, apronFt: 30, surface: 'asphalt', insideWall: false, pkg: 'plate',
    pole: { mph: 182.09, year: '2022-25 avg', series: 'Cup', fit: true }, shape: 'tri', sf: 'bulge', infield: 'lake' },
  { id: 'talladega', name: 'Talladega Superspeedway', short: 'Talladega', lat: 33.5669, lon: -86.0661, miles: 2.66,
    banking: { turns: [33, 33], front: 17, back: 3 }, widthFt: 48, apronFt: 30, surface: 'asphalt', insideWall: false, pkg: 'plate',
    pole: { mph: 182.174, year: 2025, series: 'Cup', fit: true }, shape: 'tri', sf: 'bulge' },
  { id: 'atlanta', name: 'Atlanta Motor Speedway', short: 'Atlanta', lat: 33.3836, lon: -84.3169, miles: 1.54,
    banking: { turns: [28, 28], front: 5, back: 5 }, widthFt: 40, apronFt: 15, surface: 'asphalt', insideWall: false, pkg: 'plate',
    pole: { mph: 179.371, year: 2025, series: 'Cup', fit: true }, shape: 'quad', sf: 'bulge' },

  // ---- big and intermediate ovals: 670 hp ----
  { id: 'michigan', name: 'Michigan International Speedway', short: 'Michigan', lat: 42.0664, lon: -84.2414, miles: 2.0,
    banking: { turns: [18, 18], front: 12, back: 5 }, widthFt: 73, apronFt: 20, surface: 'asphalt', insideWall: false, pkg: '670',
    pole: { mph: 195.514, year: 2025, series: 'Cup', fit: true }, shape: 'd', sf: 'bulge' },
  { id: 'pocono', name: 'Pocono Raceway', short: 'Pocono', lat: 41.0553, lon: -75.5114, miles: 2.5,
    banking: { turns: [14, 8, 6], front: 0, back: 0 }, widthFt: 60, apronFt: 15, surface: 'asphalt', insideWall: false, pkg: '670',
    pole: { mph: 172.599, year: 2025, series: 'Cup', fit: true }, shape: 'triangle', sf: 'longest' },
  { id: 'indianapolis', name: 'Indianapolis Motor Speedway', short: 'Indianapolis', lat: 39.7950, lon: -86.2347, miles: 2.5,
    banking: { turns: [9, 9, 9, 9], front: 0, back: 0 }, widthFt: 55, apronFt: 12, surface: 'asphalt', insideWall: false, pkg: '670',
    pole: { mph: 183.165, year: 2025, series: 'Cup', fit: true }, shape: 'rectangle', sf: 'longest' },
  { id: 'fontana', name: 'Auto Club Speedway', short: 'Fontana', lat: 34.0886, lon: -117.5003, miles: 2.0,
    banking: { turns: [14, 14], front: 11, back: 3 }, widthFt: 75, apronFt: 20, surface: 'asphalt', insideWall: false, pkg: '670',
    pole: { mph: 179.614, year: 2020, series: 'Cup (Gen 6)', fit: false }, shape: 'd', sf: 'bulge' },
  { id: 'charlotte', name: 'Charlotte Motor Speedway', short: 'Charlotte', lat: 35.3519, lon: -80.6828, miles: 1.5,
    banking: { turns: [24, 24], front: 5, back: 5 }, widthFt: 60, apronFt: 15, surface: 'asphalt', insideWall: false, pkg: '670',
    pole: { mph: 183.50, year: '2022-25 avg', series: 'Cup', fit: true }, shape: 'quad', sf: 'bulge' },
  { id: 'texas', name: 'Texas Motor Speedway', short: 'Texas', lat: 33.0372, lon: -97.2814, miles: 1.5,
    banking: { turns: [20, 24], front: 5, back: 5 }, widthFt: 60, apronFt: 15, surface: 'asphalt', insideWall: false, pkg: '670',
    pole: { mph: 191.659, year: 2025, series: 'Cup', fit: true }, shape: 'quad', sf: 'bulge' },
  { id: 'lasvegas', name: 'Las Vegas Motor Speedway', short: 'Las Vegas', lat: 36.2719, lon: -115.0106, miles: 1.5,
    banking: { turns: [20, 20], front: 12, back: 9 }, widthFt: 60, apronFt: 15, surface: 'asphalt', insideWall: false, pkg: '670',
    pole: { mph: 185.19, year: '2022-25 avg', series: 'Cup', fit: true }, shape: 'tri', sf: 'bulge' },
  { id: 'kansas', name: 'Kansas Speedway', short: 'Kansas', lat: 39.1156, lon: -94.8311, miles: 1.5,
    banking: { turns: [[17, 20], [17, 20]], front: 10, back: 5 }, widthFt: 55, apronFt: 15, surface: 'asphalt', insideWall: false, pkg: '670',
    pole: { mph: 180.078, year: 2025, series: 'Cup', fit: true }, shape: 'tri', sf: 'bulge' },
  { id: 'homestead', name: 'Homestead-Miami Speedway', short: 'Homestead', lat: 25.4519, lon: -80.4089, miles: 1.5,
    banking: { turns: [[18, 20], [18, 20]], front: 3, back: 3 }, widthFt: 60, apronFt: 15, surface: 'asphalt', insideWall: false, pkg: '670',
    pole: { mph: 168.845, year: 2025, series: 'Cup', fit: true }, shape: 'oval', sf: 'longest' },
  { id: 'chicagoland', name: 'Chicagoland Speedway', short: 'Chicagoland', lat: 41.4747, lon: -88.0578, miles: 1.5,
    banking: { turns: [18, 18], front: 11, back: 5 }, widthFt: 55, apronFt: 15, surface: 'asphalt', insideWall: false, pkg: '670',
    pole: { mph: 176.263, year: 2019, series: 'Cup (Gen 6)', fit: false }, shape: 'd', sf: 'bulge' },
  { id: 'kentucky', name: 'Kentucky Speedway', short: 'Kentucky', lat: 38.7114, lon: -84.9172, miles: 1.5,
    banking: { turns: [17, 14], front: 8, back: 4 }, widthFt: 55, apronFt: 15, surface: 'asphalt', insideWall: false, pkg: '670',
    pole: { mph: 190.282, year: 2017, series: 'Cup (Gen 6)', fit: false }, shape: 'd', sf: 'bulge' },
  { id: 'nashville', name: 'Nashville Superspeedway', short: 'Nashville SS', lat: 36.0453, lon: -86.4089, miles: 1.333,
    banking: { turns: [14, 14], front: 8, back: 5 }, widthFt: 55, apronFt: 15, surface: 'concrete', insideWall: false, pkg: '670',
    pole: { mph: 164.395, year: 2025, series: 'Cup', fit: true }, shape: 'tri', sf: 'bulge' },
  { id: 'darlington', name: 'Darlington Raceway', short: 'Darlington', lat: 34.2953, lon: -79.9056, miles: 1.366,
    banking: { turns: [25, 23], front: 3, back: 2 }, widthFt: 50, apronFt: 12, surface: 'asphalt', insideWall: false, pkg: '670',
    pole: { mph: 171.381, year: 2025, series: 'Cup', fit: true }, shape: 'egg', sf: 'longest' },

  // ---- short and flat tracks: 670 hp ----
  { id: 'rockingham', name: 'Rockingham Speedway', short: 'Rockingham', lat: 34.9739, lon: -79.6100, miles: 1.017,
    banking: { turns: [22, 25], front: 8, back: 8 }, widthFt: 60, apronFt: 15, surface: 'asphalt', insideWall: false, pkg: '670',
    pole: { mph: 156.475, year: 2004, series: 'Cup (Gen 4)', fit: false }, shape: 'oval', sf: 'longest' },
  { id: 'dover', name: 'Dover Motor Speedway', short: 'Dover', lat: 39.1900, lon: -75.5300, miles: 1.0,
    banking: { turns: [24, 24], front: 9, back: 9 }, widthFt: 45, apronFt: 10, surface: 'concrete', insideWall: true, pkg: '670',
    pole: { mph: 162.191, year: 2024, series: 'Cup', fit: true }, shape: 'oval', sf: 'longest' },
  { id: 'phoenix', name: 'Phoenix Raceway', short: 'Phoenix', lat: 33.3753, lon: -112.3111, miles: 1.0,
    banking: { turns: [8, 10.5, 10.5], front: 3, back: 3 }, widthFt: 52, apronFt: 20, surface: 'asphalt', insideWall: false, pkg: '670',
    pole: { mph: 133.759, year: 2025, series: 'Cup', fit: true }, shape: 'dogleg', sf: 'longest' },
  { id: 'newhampshire', name: 'New Hampshire Motor Speedway', short: 'New Hampshire', lat: 43.3628, lon: -71.4606, miles: 1.058,
    banking: { turns: [[2, 7], [2, 7]], front: 1, back: 1 }, widthFt: 60, apronFt: 20, surface: 'asphalt', insideWall: false, pkg: '670',
    pole: { mph: 130.622, year: 2025, series: 'Cup', fit: true }, shape: 'paperclip', sf: 'longest' },
  { id: 'gateway', name: 'World Wide Technology Raceway', short: 'Gateway', lat: 38.6506, lon: -90.1356, miles: 1.25,
    banking: { turns: [11, 9], front: 3, back: 3 }, widthFt: 55, apronFt: 15, surface: 'asphalt', insideWall: false, pkg: '670',
    pole: { mph: 139.190, year: 2025, series: 'Cup', fit: true }, shape: 'egg', sf: 'longest' },
  { id: 'milwaukee', name: 'Milwaukee Mile', short: 'Milwaukee', lat: 43.0194, lon: -88.0108, miles: 1.015,
    banking: { turns: [9, 9], front: 2, back: 2 }, widthFt: 60, apronFt: 10, surface: 'asphalt', insideWall: true, pkg: '670',
    pole: { mph: 122.556, year: 2024, series: 'Truck', fit: false }, shape: 'oval', sf: 'longest' },
  { id: 'iowa', name: 'Iowa Speedway', short: 'Iowa', lat: 41.6800, lon: -93.0153, miles: 0.875,
    banking: { turns: [[12, 14], [12, 14]], front: 10, back: 4 }, widthFt: 55, apronFt: 12, surface: 'asphalt', insideWall: false, pkg: '670',
    pole: { mph: 136.933, year: 2025, series: 'Cup', fit: true }, shape: 'd', sf: 'bulge' },
  { id: 'richmond', name: 'Richmond Raceway', short: 'Richmond', lat: 37.5925, lon: -77.4194, miles: 0.75,
    banking: { turns: [14, 14], front: 8, back: 2 }, widthFt: 55, apronFt: 12, surface: 'asphalt', insideWall: false, pkg: '670',
    pole: { mph: 121.381, year: 2025, series: 'Cup', fit: true }, shape: 'd', sf: 'bulge' },
  { id: 'bristol', name: 'Bristol Motor Speedway', short: 'Bristol', lat: 36.5156, lon: -82.2569, miles: 0.533,
    banking: { turns: [[26, 30], [26, 30]], front: 8, back: 8 }, widthFt: 40, apronFt: 10, surface: 'concrete', insideWall: true, pkg: '670',
    pole: { mph: 128.675, year: 2025, series: 'Cup', fit: true }, shape: 'oval', sf: 'longest' },
  { id: 'martinsville', name: 'Martinsville Speedway', short: 'Martinsville', lat: 36.6342, lon: -79.8519, miles: 0.526,
    banking: { turns: [12, 12], front: 0, back: 0 }, widthFt: 55, apronFt: 15, surface: 'asphalt', insideWall: true, pkg: '670',
    pole: { mph: 96.034, year: 2025, series: 'Cup', fit: true }, shape: 'paperclip', sf: 'longest' },
  { id: 'northwilkesboro', name: 'North Wilkesboro Speedway', short: 'N. Wilkesboro', lat: 36.1428, lon: -81.0717, miles: 0.625,
    banking: { turns: [14, 14], front: 3, back: 3 }, widthFt: 50, apronFt: 10, surface: 'asphalt', insideWall: true, pkg: '670',
    pole: { mph: 117, year: 'approx', series: 'Cup', fit: false }, shape: 'oval', sf: 'longest',
    // OSM's way named "North Wilkesboro Speedway" is drawn 0.526 mi (probably along the inside edge): right shape, scaled up
    lengthTolerance: 0.2 },
  { id: 'irp', name: 'Lucas Oil Indianapolis Raceway Park', short: 'IRP', lat: 39.8097, lon: -86.3381, miles: 0.686,
    banking: { turns: [12, 12], front: 0, back: 0 }, widthFt: 50, apronFt: 10, surface: 'asphalt', insideWall: true, pkg: '670',
    pole: { mph: 118, year: 'approx', series: 'Truck', fit: false }, shape: 'oval', sf: 'longest' },
  { id: 'bowmangray', name: 'Bowman Gray Stadium', short: 'Bowman Gray', lat: 36.0844, lon: -80.2244, miles: 0.25,
    banking: { turns: [3, 3], front: 0, back: 0 }, widthFt: 35, apronFt: 5, surface: 'asphalt', insideWall: true, pkg: '670',
    pole: { mph: 63.762, year: 2025, series: 'Cup', fit: true }, shape: 'oval', sf: 'longest' },
  { id: 'memphis', name: 'Memphis International Raceway', short: 'Memphis', lat: 35.2814, lon: -89.9469, miles: 0.75,
    banking: { turns: [11, 11], front: 6, back: 6 }, widthFt: 55, apronFt: 12, surface: 'asphalt', insideWall: false, pkg: '670',
    pole: { mph: 122, year: 'approx', series: 'Xfinity', fit: false }, shape: 'oval', sf: 'longest' },
  { id: 'fairgrounds', name: 'Nashville Fairgrounds Speedway', short: 'Fairgrounds', lat: 36.1328, lon: -86.7631, miles: 0.596,
    banking: { turns: [18, 18], front: 14, back: 14 }, widthFt: 45, apronFt: 10, surface: 'asphalt', insideWall: true, pkg: '670',
    pole: { mph: 115, year: 'approx', series: 'Xfinity', fit: false }, shape: 'oval', sf: 'longest' },
  { id: 'pikespeak', name: 'Pikes Peak International Raceway', short: 'Pikes Peak', lat: 38.5833, lon: -104.6750, miles: 1.0,
    banking: { turns: [10, 10], front: 8, back: 3 }, widthFt: 55, apronFt: 15, surface: 'asphalt', insideWall: false, pkg: '670',
    pole: { mph: 148, year: 'approx', series: 'Xfinity', fit: false }, shape: 'd', sf: 'bulge' },
];

module.exports = { SPECS };
