#!/usr/bin/env node
// Assembles train/nn.wat into js/nn-wasm.js, the module inlined as base64 so the browser, the trainer and
// remote workers all load it synchronously with nothing to install. Only needed after editing nn.wat:
//   node train/build-nn.js
const { execFileSync } = require('child_process');
const fs = require('fs');
const os = require('os');
const path = require('path');

const wasm = path.join(os.tmpdir(), `nn-${process.pid}.wasm`);
execFileSync('npx', ['-y', '-p', 'wabt@1.0.39', 'wat2wasm', path.join(__dirname, 'nn.wat'), '-o', wasm], { stdio: 'inherit' });
const bytes = fs.readFileSync(wasm);
fs.rmSync(wasm);
fs.writeFileSync(path.join(__dirname, '..', 'js', 'nn-wasm.js'),
  `// generated by train/build-nn.js from train/nn.wat; don't edit\nconst NN_WASM = '${bytes.toString('base64')}';\n`);
console.log(`js/nn-wasm.js: ${bytes.length}-byte module`);
